name: 'Check typescript code'
description: 'Checks typescript code and runs tests.'
inputs:
  project:
    description: 'Which solution to run tests on.'
    required: true
runs:
  using: "composite"
  steps:
  - name: check code
    run: npm install
    working-directory: ${{ inputs.project }}
    shell: bash
  - name: run tests
    run: npm run test
    working-directory: ${{ inputs.project }}
    shell: bash
  - name: build code
    run: npm run build
    working-directory: ${{ inputs.project }}
    shell: bash
