name: 'Check code'
description: 'Checks code and runs tests, filtered by group name; unit, integration or end-to-end tests.'
inputs:
  project:
    description: 'Which solution to run tests on.'
    required: true
  unit:
    description: 'Run unit tests?'
    type: boolean
    required: true
    default: false
  integration:
    description: 'Run integration tests?'
    type: boolean
    required: true
    default: false
  e2e:
    description: 'Run e2e tests?'
    type: boolean
    required: true
    default: false
runs:
  using: "composite"
  steps:
  - name: create local package source "locals"
    run: |
      if [ ! -d "${{ inputs.project }}/locals" ]; then
        mkdir "${{ inputs.project }}/locals"
      fi
    shell: bash
  - name: check code
    run: dotnet format ${{ inputs.project }} --verify-no-changes --no-restore
    shell: bash
  - name: build code
    run: |
      dotnet build ${{ inputs.project }} --configuration Debug
    shell: bash
  - name: run unit tests
    if: ${{ inputs.unit }}
    run: dotnet test ${{ inputs.project }} --filter Category=Unit --no-build
    shell: bash
  - name: run integration tests
    if: ${{ inputs.integration }}
    run: dotnet test ${{ inputs.project }} --filter Category=Integration --no-build
    shell: bash
  - name: run end-to-end tests
    if: ${{ inputs.e2e }}
    run: dotnet test ${{ inputs.project }} --filter Category=EndToEnd --no-build
    shell: bash
