name: 'Run tests'
description: 'Runs tests, filtered by group name; unit, integration or end-to-end tests.'
inputs:
  solution:
    description: 'Which solution to run tests on.'
    required: true
  unit:
    description: 'Run unit tests?'
    type: boolean
    required: true
    default: false
  integration:
    description: 'Run integration tests?'
    type: boolean
    required: true
    default: false
  e2e:
    description: 'Run e2e tests?'
    type: boolean
    required: true
    default: false
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: run unit tests
    if: ${{ inputs.unit }}
    run: dotnet test ${{ inputs.solution }} --filter TestCategory=Unit
    shell: bash
  - name: run integration tests
    if: ${{ inputs.integration }}
    run: dotnet test ${{ inputs.solution }} --filter TestCategory=Integration
    shell: bash
  - name: run end-to-end tests
    if: ${{ inputs.e2e }}
    run: dotnet test ${{ inputs.solution }} --filter TestCategory=E2E
    shell: bash
