name: Pull request to staging
run-name: ${{ github.actor }} has created a pull request from ${{ github.head_ref }} to ${{ github.base_ref }}
on:
  pull_request:
    branches: staging
jobs:
  check-from-main:
    runs-on: ubuntu-latest
    steps:
      - name: check from main
        if: ${{ github.head_ref != 'main' }}
        run: exit 1
  verify-frontend-code:
    runs-on: ubuntu-latest
    needs: [check-from-main]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-code
        with:
          project: frontend
          unit: true
          integration: true
          e2e: false # We run these specifically on staging
