name: Pull request to main
run-name: ${{ github.actor }} has created a pull request from ${{ github.head_ref }} to ${{ github.base_ref }}
on:
  pull_request:
    branches: main
env:
  GH_TOKEN: ${{ github.token }}
permissions:
  pull-requests: read
  contents: read
  id-token: write
jobs:
  detect-files-changed:
    outputs:
      backend-files-changed: ${{ steps.get-files-changed.outputs.backend-files-changed }}
      frontend-files-changed: ${{ steps.get-files-changed.outputs.frontend-files-changed }}
      iac-files-changed: ${{ steps.get-files-changed.outputs.iac-files-changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Files changed
        id: get-files-changed
        run: |
          echo backend-files-changed=false >> $GITHUB_OUTPUT
          echo frontend-files-changed=false >> $GITHUB_OUTPUT
          echo iac-files-changed=false >> $GITHUB_OUTPUT

          paths=$(gh pr view --json files -q '.files[].path')

          for path in $paths; do
            if [[ $path == backend/* ]]; then
              echo backend-files-changed=true >> $GITHUB_OUTPUT
            fi
            if [[ $path == frontend/* ]]; then
              echo frontend-files-changed=true >> $GITHUB_OUTPUT
            fi
            if [[ $path == iac/* ]]; then
              echo iac-files-changed=true >> $GITHUB_OUTPUT
            fi
          done
  verify-backend-code:
    runs-on: ubuntu-latest
    environment: development
    needs: [detect-files-changed]
    if: ${{ needs.detect-files-changed.outputs.backend-files-changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.302' # Matches local development environment
      - uses: ./.github/actions/check-dotnet-code
        with:
          project: backend
  verify-frontend-code:
    runs-on: ubuntu-latest
    environment: development
    needs: [detect-files-changed]
    if: ${{ needs.detect-files-changed.outputs.frontend-files-changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-typescript-code
        with:
          project: frontend
  verify-iac:
    runs-on: ubuntu-latest
    environment: staging
    needs: [detect-files-changed]
    if: ${{ needs.detect-files-changed.outputs.iac-files-changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ASSUMABLE_ROLE }}
      - uses: hashicorp/setup-terraform@v3
      - uses: ./.github/actions/check-terraform
        with:
          project: ./iac/terraform
