name: Pull request to staging
run-name: ${{ github.actor }} has created a pull request from ${{ github.head_ref }} to ${{ github.base_ref }}
on:
  pull_request:
    branches: staging
env:
  GH_TOKEN: ${{ github.token }}
permissions:
  contents: read
  id-token: write
jobs:
  check-from-main:
    runs-on: ubuntu-latest
    steps:
      - name: check from main
        if: ${{ github.head_ref != 'main' }}
        run: exit 1
  verify-backend-code:
    runs-on: ubuntu-latest
    environment: development
    needs: [check-from-main]    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.302' # Matches local development environment
      - uses: ./.github/actions/check-dotnet-code
        with:
          project: backend
  verify-frontend-code:
    runs-on: ubuntu-latest
    environment: development
    needs: [check-from-main]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-typescript-code
        with:
          project: frontend
          unit: true
          integration: true
          e2e: false # We run these specifically on staging
  verify-iac:
    runs-on: ubuntu-latest
    environment: staging
    needs: [check-from-main]
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ASSUMABLE_ROLE }}
      - uses: hashicorp/setup-terraform@v3
      - uses: ./.github/actions/check-terraform
        with:
          project: ./iac/terraform
