name: Run end to end tests
run-name: ${{ github.actor }} has requested end to end tests to be run ${{ github.sha }}
on:
  workflow_dispatch
jobs:
  verify-frontend-code:
    concurrency:
      group: e2e-tests
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.302' # Matches local development environment
      - uses: ./.github/actions/check-code
        with:
          project: frontend
          unit: false
          integration: false
          e2e: true
