name: Run end to end tests
run-name: ${{ github.actor }} has requested end to end tests to be run ${{ github.sha }}
on:
  workflow_dispatch
jobs:
  verify-frontend-code:
    concurrency:
      e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-code
        with:
          project: frontend
          unit: false
          integration: false
          e2e: true
